name: tagpr
on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: Songmu/tagpr@b3fb89424646b06c8aa460f50307c60b6a541425 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
